import type { User, Event, DashboardStats, ChartDataPoint, ActivityItem, Transaction } from '../types'

export const mockStats: DashboardStats = {
  totalEvents: 1482,
  activeEvents: 342,
  pendingEvents: 12,
  totalRevenue: 42500000,
  ticketSales: 8200,
  totalUsers: 12400,
  newUsersThisWeek: 124,
  verifiedOrganizers: 482,
  pendingReviews: 12,
  suspendedUsers: 8,
  growth: 12.5,
}

export const mockUserGrowth: ChartDataPoint[] = [
  { month: 'JAN', value: 320 },
  { month: 'FEB', value: 480 },
  { month: 'MAR', value: 550 },
  { month: 'APR', value: 620 },
  { month: 'MAY', value: 710 },
  { month: 'JUN', value: 780 },
  { month: 'JUL', value: 980 },
  { month: 'AUG', value: 860 },
  { month: 'SEP', value: 920 },
  { month: 'OCT', value: 870 },
  { month: 'NOV', value: 950 },
]

export const mockActivity: ActivityItem[] = [
  {
    id: '1',
    type: 'organizer',
    title: 'New Organizer Registered',
    description: 'Innovate Togo Ltd. has been verified as a premium organizer.',
    time: '2 mins ago',
  },
  {
    id: '2',
    type: 'event',
    title: 'Event Approved',
    description: '"AI in Agriculture Workshop" is now live on the public dashboard.',
    time: '2 mins ago',
  },
  {
    id: '3',
    type: 'warning',
    title: 'System Warning',
    description: 'Spike in failed login attempts from IP 196.20.x.x',
    time: '40 mins ago',
  },
  {
    id: '4',
    type: 'campaign',
    title: 'Campaign Launched',
    description: 'Newsletter sent to 12,400 subscribers for Tech Excellence Week.',
    time: 'Yesterday',
  },
]

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Lomé Web3 Summit 2026',
    organizer: 'InnovateTogo',
    location: 'Palais des Congrès, Lomé',
    date: '12 Oct',
    category: 'WEB3 & FINTECH',
    status: 'Live',
    attendees: 320,
    image: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400&h=200&fit=crop',
  },
  {
    id: '2',
    title: 'Ethical AI in Agriculture',
    organizer: 'TechTogo Hub',
    location: 'Espace Digital, Lomé',
    date: '18 Oct',
    category: 'AI WORKSHOP',
    status: 'Pending',
    attendees: 0,
  },
  {
    id: '3',
    title: 'Exclusive Startup Gala',
    organizer: 'StartupTg',
    location: 'Hotel 2 Février',
    date: '24 Oct',
    category: 'BUSINESS',
    status: 'Flagged',
    attendees: 450,
    flagReason: 'Reported for misleading information regarding ticketing prices and official sponsorship.',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=200&fit=crop',
  },
  {
    id: '4',
    title: 'Lomé Crypto Summit',
    organizer: 'CryptoTG',
    location: 'Palais des Congrès',
    date: '12 Oct',
    category: 'FINTECH',
    status: 'Live',
    attendees: 120,
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=400&h=200&fit=crop',
  },
  {
    id: '5',
    title: 'Founders Night',
    organizer: 'StartupHub TG',
    location: 'Blue Zone',
    date: '24 Oct',
    category: 'NETWORKING',
    status: 'Past',
    attendees: 45,
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400&h=200&fit=crop',
  },
  {
    id: '6',
    title: 'DevFest Lomé 2026',
    organizer: 'GDG Lomé',
    location: 'Maison des Jeunes',
    date: '30 Nov',
    category: 'TECH',
    status: 'Live',
    attendees: 680,
    image: 'https://images.unsplash.com/photo-1540575861501-7cf05a4b125a?w=400&h=200&fit=crop',
  },
]

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Afiwa Dogbe',
    email: 'afiwa.dogbe@tech-togo.com',
    role: 'ORGANIZER',
    status: 'Active',
    joinedAt: 'Oct 12, 2025',
    avatar: 'https://i.pravatar.cc/150?img=47',
  },
  {
    id: '2',
    name: 'Komla Edoh',
    email: 'komla.edoh@hub.tg',
    role: 'USER',
    status: 'Active',
    joinedAt: 'Sep 28, 2025',
    avatar: 'https://i.pravatar.cc/150?img=12',
  },
  {
    id: '3',
    name: 'Essi Lawson',
    email: 'essi.lawson@private.me',
    role: 'USER',
    status: 'Suspended',
    joinedAt: 'Aug 05, 2025',
    avatar: 'https://i.pravatar.cc/150?img=45',
  },
  {
    id: '4',
    name: 'Yaw Aziave',
    email: 'yaw.aziave@finance-hub.tg',
    role: 'ORGANIZER',
    status: 'Active',
    joinedAt: 'Nov 22, 2025',
    avatar: 'https://i.pravatar.cc/150?img=33',
  },
  {
    id: '5',
    name: 'Koami Tetteh',
    email: 'koami.tetteh@innov.tg',
    role: 'ORGANIZER',
    status: 'Active',
    joinedAt: 'Jul 14, 2025',
    avatar: 'https://i.pravatar.cc/150?img=61',
  },
  {
    id: '6',
    name: 'Mawuli Doe',
    email: 'mawuli.doe@startup.tg',
    role: 'USER',
    status: 'Active',
    joinedAt: 'Oct 01, 2025',
    avatar: 'https://i.pravatar.cc/150?img=68',
  },
  {
    id: '7',
    name: 'Kafui Gomado',
    email: 'kafui.gomado@tech.tg',
    role: 'USER',
    status: 'Pending',
    joinedAt: 'Nov 30, 2025',
    avatar: 'https://i.pravatar.cc/150?img=22',
  },
  {
    id: '8',
    name: 'Ama Koffi',
    email: 'ama.koffi@gdg.tg',
    role: 'ORGANIZER',
    status: 'Active',
    joinedAt: 'Aug 20, 2025',
    avatar: 'https://i.pravatar.cc/150?img=56',
  },
]

export const mockTransactions: Transaction[] = [
  { id: 'TXN-001', event: 'Lomé Web3 Summit', organizer: 'InnovateTogo', amount: 1200000, date: 'Oct 12, 2025', status: 'Completed' },
  { id: 'TXN-002', event: 'DevFest Lomé 2026', organizer: 'GDG Lomé', amount: 850000, date: 'Nov 30, 2025', status: 'Pending' },
  { id: 'TXN-003', event: 'Lomé Crypto Summit', organizer: 'CryptoTG', amount: 620000, date: 'Oct 12, 2025', status: 'Completed' },
  { id: 'TXN-004', event: 'Founders Night', organizer: 'StartupHub TG', amount: 320000, date: 'Oct 24, 2025', status: 'Completed' },
  { id: 'TXN-005', event: 'Exclusive Startup Gala', organizer: 'StartupTg', amount: 950000, date: 'Oct 24, 2025', status: 'Refunded' },
]

export const mockRevenueByMonth: ChartDataPoint[] = [
  { month: 'JAN', value: 2100000 },
  { month: 'FEB', value: 3200000 },
  { month: 'MAR', value: 2800000 },
  { month: 'APR', value: 4100000 },
  { month: 'MAY', value: 3700000 },
  { month: 'JUN', value: 5200000 },
  { month: 'JUL', value: 6800000 },
  { month: 'AUG', value: 5400000 },
  { month: 'SEP', value: 6200000 },
  { month: 'OCT', value: 5800000 },
  { month: 'NOV', value: 7100000 },
]
